[tool]
[tool.poetry]
name = "metaL"
version = "0.0.1"
description = "[meta]programming [L]anguage"
authors = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
[tool.poetry.dependencies]
python = "^3.7"
ply = "^3.11"
xxhash = "^1.4"
[tool.poetry.dev-dependencies]
autopep8 = ""
pytest = ""
